/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: "https://www.docya.com.ar",
  generateRobotsTxt: true,
  sitemapSize: 5000,
  changefreq: "weekly",
  priority: 0.8,
  exclude: [
    "/404",
    "/_error",
    "/admin",
    "/login",
    "/gracias",
    "/pedir/filtro",
    "/pedir/pago",
    "/pedir/consultas",
    "/pedir/buscando",
    "/pedir/pago_resultado",
    "/pedir/solicitar",
    "/pedir/perfil",
    "/pedir/videollamada",
    "/recetario/login",
    "/recetario/completar-perfil",
    "/recetario/cuenta-en-revision",
    "/recetario/dashboard",
    "/recetario/dashboard/*",
    "/referidos/login",
    "/referidos/link",
    "/referidos/cobros",
    "/referidos/mis-referidos",
    "/referidos/panel",
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: "/",
      },
    ],
  },
};
